### ISSUE TITLE
can't load library: java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by andyczerwonka** [playframework/play-scala-kalium-example#1]
Hi Will,

Thanks for putting this example together.

I'm running into a problem where I can't load the native library. Any thoughts on this? 

```
An exception or error caused a run to abort: libsodium.so: cannot open shared object file: No such file or directory 
java.lang.UnsatisfiedLinkError: libsodium.so: cannot open shared object file: No such file or directory
    at jnr.ffi.provider.jffi.NativeLibrary.loadNativeLibraries(NativeLibrary.java:87)
    at jnr.ffi.provider.jffi.NativeLibrary.getNativeLibraries(NativeLibrary.java:70)
    at jnr.ffi.provider.jffi.NativeLibrary.getSymbolAddress(NativeLibrary.java:49)
    at jnr.ffi.provider.jffi.NativeLibrary.findSymbolAddress(NativeLibrary.java:59)
    at jnr.ffi.provider.jffi.AsmLibraryLoader.generateInterfaceImpl(AsmLibraryLoader.java:117)
    at jnr.ffi.provider.jffi.AsmLibraryLoader.loadLibrary(AsmLibraryLoader.java:59)
    at jnr.ffi.provider.jffi.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:43)
    at jnr.ffi.LibraryLoader.load(LibraryLoader.java:265)
    at jnr.ffi.LibraryLoader.load(LibraryLoader.java:244)
    at org.abstractj.kalium.NaCl$SingletonHolder.<clinit>(NaCl.java:41)
    at org.abstractj.kalium.NaCl.sodium(NaCl.java:28)
    at org.abstractj.kalium.crypto.Random.randomBytes(Random.java:33)
    at services.encryption.Nonce$.createNonce(KaliumEncryptionService.scala:50)
    at services.encryption.KaliumEncryptionService.encrypt(KaliumEncryptionService.scala:23)
```

**Comment by wsargent** [comment]
Did you install libsodium?

**Comment by andyczerwonka** [comment]
I thought I did, so thanks for the heads up. I needed to install `libsodium-dev`, I only installed `libsodium`.
